name: snackautomat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  flutter_secure_storage: ^5.1.2
  crypto: ^3.0.1
  flutter_glow: ^0.3.2
  animated_text_kit: ^4.2.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/coins/
    - assets/products/
    - assets/Vendor/
    - assets/wallet/
    - assets/sounds/coinsound.mp3
    - assets/sounds/vending-machine-output.mp3